# Generated by Django 4.2.3 on 2023-08-16 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_avito', '0003_avito_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='avito',
            name='image',
            field=models.ImageField(default=' ', upload_to='avitos/', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
